name: M4mlops
channels: 
 - conda-forge
dependencies:
    - python=3.10
    - pip
    - mlflow=2.17.2
    - kaggle=1.6.17
    - notebook=7.2.2
    - pandas=2.2.3
    - scikit-learn=1.5.2
    - xgboost=2.1.2
    - pip:
      - imblearn==0.0