name: bike-share
channels:
 - conda-forge
dependencies:
  - python=3.12
  - pip
  - dagster-webserver=1.9.4
  - dagster=1.9.4
  - mlflow=2.18.0
  - jupyter
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - xgboost=2.1.3